### ISSUE TITLE
Pick a command pattern and stick with it

### ISSUE THREAD

**Issue by jasonroelofs** [pantry/pantry#10]
Trying to decide on a good command api naming pattern. Currently going with rake-esque, though order is tough to get right:
- chef:cookbook:upload
- chef:upload:cookbook
- chef:sync:cookbooks
- echo
- ... etc

**Comment by emilford** [comment]
I personally like `chef:<thing>:<action>` over `chef:<action>:<thing>`.  That hierarchy order makes more sense to me.

**Comment by jasonroelofs** [comment]
Aye, I do to but in local use I find myself regularly typing out `chef:<action>:<thing>` which I don't really understand. 

But maybe that's just me. :confused:

**Comment by emilford** [comment]
Maybe more focused on the action than what the action is being performed against?  Makes sense then that it'd jump ahead.

**Comment by jasonroelofs** [comment]
Aye though even the knife commands are `knife cookbook upload [cookbook name]`. Also when other handlers come into play I want to make sure we keep consistency:
- docker:[something?]:upload
- docker:upload:[something?]

There's also the singular / plural question. `chef:cookbooks:upload` reads better than `chef:upload:cookbooks` when the command takes just a single cookbook (though can probably be easily updated to take multiple).

**Comment by jasonroelofs** [comment]
Ya, going with `<tool>:<thing>:<action>`.
